# project name
name="yugong"
debug=true


[celery]
broker="redis://localhost:6379/0"
backend="redis://localhost:6379/1"

[log]
# Available settings: single/daily
type="single"

# Available settings: debug/info/notice/warning/error/critical
level="debug"

# Available settings: file/stdout/stderr
#driver="stderr"
driver = "file"

# utc/local
datetime_format="local"

[redis]
host="localhost"
port=6379
db=0

[toutiao]
account=""
password=""
access_token="token"
client_key = "key"
client_secret="secret"
notify_receiver=""
nofity_url="XXX/a.php?img=%s&key=%s"

[qiniu]
access_key="key"
secret_key="key"
bucket="toutiao"
#domain="http://cdn-td.xiaolewei.com/"
domain="domain"

[mail]
account="act"
password="pwd"